language: node_js
node_js:
    - "stable"

script:
    - npm i -g hexo
    - hexo init --help
    - hexo --help
    - hexo init pages && cd pages
    - npm install
    - cp -r ../articles/* ./source/_posts
    - hexo generate
    - ls -al

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: temp/pages/public
    on:
        branch: master

