language: node_js
node_js:
    - "stable"

cache:
    directories:
        - node_modules

script:
    - npm i -g hexo
    - hexo init pages && cd pages
    - npm install
    - cp -r ../articles/* ./source/_posts
    - hexo generate

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: pages/public
    on:
        branch: master

