language: node_js
node_js:
    - "stable"

scripts:
    - npm i -g hexo
    - hexo init --help
    - hexo --help
    - mkdir temp && cd temp
    - hexo init pages && cd pages
    - npm install
    - hexo generate
    - ls -al

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $gh_token
    local_dri: temp/pages/public
    on:
        branch: master

