title: Articles of daily research
author: Mingshi
language: en

url: https://blog.unoiou.com/articles
root: /articles/
permalink: :year/:month/:day/:title/

SEOTitle: "Refined articles of daily research - Mingshi's blog" 
email: cmsax@live.com
description: "Articles about coding, quantitative transaction, natuaral language processing and daily records."
keyword: "Mingshi, cmsax, nlp, quant, blog"

sidebar-img: ${sidebar_img_url}

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories

theme: ${theme_name}

search:
    path: search.json
    field: post

weibo_username: cmsax
github_username: cmsax

per_page: 5
pagination_dir: page

