title: ${hexo_title} 
author: ${hexo_author}
language: ${hexo_lang}

url: ${hexo_url}
root: ${hexo_root}
permalink: ${hexo_permalink}

SEOTitle: ${hexo_seo_title}
email: ${hexo_email}
description: ${hexo_description}

sidebar-img: ${sidebar_img_url}

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

theme: ${theme_name}

search:
    path: search.json
    field: post

weibo_username: ${hexo_author}
github_username: ${hexo_author}

per_page: 5
pagination_dir: page

feed:
  type: atom
  path: atom.xml
  limit: 5
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png

sitemap:
    path: sitemap.xml

