nav:
    Home: /
    Projects: http://github.com/cmsax
    #Search: /search/

how_all_posts: false
post_count: 5

highlight: pojoaque

rss: false

color_scheme: white

disqus:
    enabled: false

social_links:
    github: https://github.com/cmsax
    weibo: https://weibo.com/cmsax

