version: 3.0.0
logo:
  text: Articles

head:
  favicon: /img/favicon.png
  canonical_url:
    open_graph:
      title: Articles
      type: blog
      url: https://www.unoiou.com/articles/
      image: https://unoiou.com/resume/avatar.png
      site_name: Articles
      author: Mingshi Cai
      description: 一些技术总结
    structured_data:
      title: Mingshi Cai's blog
      description: About coding
  rss: /atom.xml
navbar:
  menu:
    Archives: /archives
  links:
    CV:
      icon: fa fa-file-pdf
      url: "https://unoiou.com/resume/mingshi_cai_cv.pdf"
footer:
  links:
    Build Status:
      icon: fa fa-bolt
      url: "https://travis-ci.com/github/cmsax/articles"
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
article:
  highlight:
    theme: atom-one-dark
    clipboard: true
    fold: unfolded
  thumbnail: false
  readtime: true
search:
  type: insight

share:
  type: sharejs
  install_url: ""
sidebar:
  left:
    sticky: true
  right:
    sticky: false
widgets:
  - position: left
    type: toc
  - position: left
    type: profile
    author: Mingshi Cai
    author_title:
    location: Wuhan
    avatar: https://unoiou.com/resume/avatar.png
    avatar_rounded: true
    social_links:
      Github:
        icon: fab fa-github
        url: "https://github.com/cmsax"
      Email:
        icon: fa fa-envelope
        url: "cmsgroup@whu.edu.cn"
      RSS:
        icon: fas fa-rss
        url: /atom.xml
    has_hitokoto: false

  - position: right
    type: recent_posts
  - position: right
    type: categories
  - position: right
    type: archives
  - position: right
    type: tags

plugins:
  animejs: true
  back_to_top: true
  baidu_analytics: false
  busuanzi: false
  gallery: false
  google_analytics:
    tracking_id: "UA-138733674-1"
  hotjar: false
  katex: true
  mathjax: false
  outdated_browser: false
  progressbar: true
