projects_url: ${github_url}

gravatar:
    email: ${hexo_email}

nav:
    Home: /
    Projects: ${github_url}
    Search: /search/

highlight: pojoaque

rss: 

color_scheme: white

disqus:
    enabled: false

social_links:
    github: ${github_url}
    weibo: ${weibo}

post:
    show_updated: false

archive:
    sort_updated: false

tags_overview: false

posts_overview:
    show_all_posts: true

logo:
    enabled: false

favicon:
    desktop:
        url: /images/favicon.ico
        gravatar: false
    android:
        url: /images/favicon.ico
        gravatar: false
    apple:
        url: /images/favicon.ico
        gravatar: false

page_width: 48

open_graph:
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:

google_analytics:
    enabled: false

baidu_analytics:
    enabled: false

