# Version of the configuration file
version: 3.0.0
# Path or URL to the website's logo
logo:
  text: Articles

head:
  # URL or path to the website's icon
  favicon: /img/favicon.png
  # Canonical URL of the current page
  canonical_url:
  # Open Graph metadata
  # https://hexo.io/docs/helpers.html#open-graph
  open_graph:
    # Page title (og:title) (optional)
    # You should leave this blank for most of the time
    title: Articles
    # Page type (og:type) (optional)
    # You should leave this blank for most of the time
    type: blog
    # Page URL (og:url) (optional)
    # You should leave this blank for most of the time
    url: https://www.unoiou.com/articles/
    # Page cover (og:image) (optional) Default to the Open Graph image or thumbnail of the page
    # You should leave this blank for most of the time
    image: /img/avatar.png
    # Site name (og:site_name) (optional)
    # You should leave this blank for most of the time
    site_name: Articles
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    author: Mingshi Cai
    # Page description (og:description) (optional)
    # You should leave this blank for most of the time
    description: java,技术分享,后端开发,支付框架,数据接口,算法,leetcode
    # Twitter card type (twitter:card)
    twitter_card:
    # Twitter ID (twitter:creator)
    twitter_id:
    # Twitter ID (twitter:creator)
    twitter_site:
    # Google+ profile link (deprecated)
    google_plus:
    # Facebook admin ID
    fb_admins:
    # Facebook App ID
    fb_app_id:
  # Structured data of the page
  # https://developers.google.com/search/docs/guides/intro-structured-data
  structured_data:
    # Page title (optional)
    # You should leave this blank for most of the time
    title: Mingshi Cai
    # Page description (optional)
    # You should leave this blank for most of the time
    description: About coding
    # Page URL (optional)
    # You should leave this blank for most of the time
    # Page author (article:author) (optional)
    # You should leave this blank for most of the time
    # Page images (optional) Default to the Open Graph image or thumbnail of the page
    # You should leave this blank for most of the time
  # Additional HTML meta tags in an array
  meta:
    # Meta tag specified in <attribute>=<value> style
    # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
    - ""
  # URL or path to the website's RSS atom.xml
  rss: /atom.xml
# Page top navigation bar configurations
navbar:
  # Naviagtion menu items
  menu:
    Home: /
  # Links to be shown on the right of the navigation bar

# Page footer configurations
footer:
  # Links to be shown on the right of the footer section
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: "https://creativecommons.org/"
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: "https://creativecommons.org/licenses/by/4.0/"
# Article related configurations
article:
  # Code highlight settings
  highlight:
    # Code highlight themes
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-dark
    # Show copy code button
    clipboard: true
    # Default folding status of the code blocks. Can be "", "folded", "unfolded"
    fold: folded
  # Whether to show thumbnail image for every article
  thumbnail: true
  # Whether to show estimated article reading time
  readtime: true
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
  type: insight

# # Donate plugin configurations
# donate:
#     # Alipay donate button configurations
#     -
#         # Donation entry name
#         type: alipay
#         # Qrcode image URL
#         qrcode: 'https://raw.githubusercontent.com/Mingshi Cai/blog_image/master/img/2019/20190802135456.png'
#     -
#         # Donation entry name
#         type: wechat
#         # Qrcode image URL
#         qrcode: 'https://raw.githubusercontent.com/Mingshi Cai/blog_image/master/img/2019/20190802135550.png'
# #    -
#    -
#        type: patreon
#        # URL to the Patreon page
#        url: ''
#    # Paypal donate button configurations
#    -
#        type: paypal
#        # Paypal business ID or email address
#        business: ''
#        # Currency code
#        currency_code: USD
#    # Wechat donate button configurations
#    -
#        type: wechat
#        # Wechat qrcode image URL
#        qrcode: ''
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
  type: sharejs
  # URL to the ShareThis share plugin script
  install_url: ""
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
  # Left sidebar configurations
  left:
    # Whether the sidebar sticks to the top when page scrolls
    sticky: true
  # Right sidebar configurations
  right:
    # Whether the sidebar sticks to the top when page scrolls
    sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
# 注释对应的节点，包括”-“一起注释掉，相应的widget不显示
widgets:
  - # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: toc
  # Profile widget configurations
  - # Where should the widget be placed, left sidebar or right sidebar
    position: left
    type: profile
    # Author name
    author: Mingshi Cai
    # Title of the author to be shown in the profile widget
    author_title:
    # Author's current location to be shown in the profile widget
    location: Wuhan
    # Path or URL to the avatar to be shown in the profile widget
    avatar: https://unoiou.com/resume/avatar.png
    # Whether show the rounded avatar image
    avatar_rounded: true
    # Email address for the Gravatar
    gravatar:
    # URL or path for the follow button
    social_links:
      Github:
        icon: fab fa-github
        url: "https://github.com/cmsax"
      RSS:
        icon: fas fa-rss
        url: /atom.xml
    has_hitokoto: true #左边一言开关，true-开，false-关

  # Recommendation links widget configurations
  # Table of contents widget configurations
  - position: right
    type: latest_comment
  #    -
  #        # Where should the widget be placed, left sidebar or right sidebar
  #        position: left
  #        type: links
  #        # Names and URLs of the sites
  #        links:
  #            Hexo: 'https://hexo.io'
  #            Bulma: 'https://bulma.io'
  # Recent posts widget configurations
  - # Where should the widget be placed, left sidebar or right sidebar
    position: right
    type: recent_posts
  # Categories widget configurations
  - # Where should the widget be placed, left sidebar or right sidebar
    position: right
    type: categories
  # Archives widget configurations
  - # Where should the widget be placed, left sidebar or right sidebar
    position: right
    type: archives
  # Tags widget configurations
  - # Where should the widget be placed, left sidebar or right sidebar
    position: right
    type: tags
  # Google FeedBurner email subscription widget configurations
  - # Where should the widget be placed, left sidebar or right sidebar
    position: right
    type: subscribe_email
    # Hint text under the email input
    description: 输入邮箱开始订阅，更博后邮件通知！
    # Feedburner ID
    feedburner_id:
  # Google AdSense unit configurations
#    -
#        # Where should the widget be placed, left sidebar or right sidebar
#        position: left
#        type: adsense
#        # AdSense client ID
#        client_id: ''
#        # AdSense AD unit ID
#        slot_id: ''
#    -
# position: right
# type: notice
# contents:
#     1: 2019.8.15 <a href="https://github.com/Mingshi Cai/hexo-theme-amazing" target="_blank">主题开源</a>
#     2: 2020.5.20 添加公告widget
#     3: 2020.5.21 公告测试
# Plugin configurations
plugins:
  # Enable page startup animations
  animejs: true
  # Show the "back to top" button
  back_to_top: true
  # Baidu Analytics plugin settings
  # https://tongji.baidu.com
  baidu_analytics:
    # Baidu Analytics tracking ID
    tracking_id:
  # BuSuanZi site/page view counter
  # https://busuanzi.ibruce.info
  busuanzi: false
  # Enable the lightGallery and Justified Gallery plugins
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
  gallery: false
  # Google Analytics plugin settings
  # https://analytics.google.com
  google_analytics:
    # Google Analytics tracking ID
    tracking_id:
  # Hotjar user feedback plugin
  # https://www.hotjar.com/
  hotjar:
    # Hotjar site id
    site_id:
  # Enable the KaTeX math typesetting supprot
  # https://katex.org/
  katex: false
  # Enable the MathJax math typesetting support
  # https://www.mathjax.org/
  mathjax: true
  # Enable the Outdated Browser plugin
  # http://outdatedbrowser.com/
  outdated_browser: false
  # Show a progress bar at top of the page on page loading
  progressbar: true
# CDN provider settings
